// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW2aMq1KvfnLYpaDMMdxb5KxkoDSCcYxo',
    appId: '1:264376487042:web:610d349702981b7850789b',
    messagingSenderId: '264376487042',
    projectId: 'match5-9f06d',
    authDomain: 'match5-9f06d.firebaseapp.com',
    storageBucket: 'match5-9f06d.firebasestorage.app',
    measurementId: 'G-TR8V299104',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-EZ_aUxLY6DBZxRY30j1wYBRs0nwLx-I',
    appId: '1:264376487042:android:3d57d92e9d00678d50789b',
    messagingSenderId: '264376487042',
    projectId: 'match5-9f06d',
    storageBucket: 'match5-9f06d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzxUD73yhL26QR7urT6KRftm9l5lgqQKQ',
    appId: '1:264376487042:ios:4800b1e94383dece50789b',
    messagingSenderId: '264376487042',
    projectId: 'match5-9f06d',
    storageBucket: 'match5-9f06d.firebasestorage.app',
    androidClientId: '264376487042-hbbqjqgmotf1d59ip7hc3vua00dht0h6.apps.googleusercontent.com',
    iosClientId: '264376487042-3obn9kb2lrh7i5sl4bnatq2723jjv3ik.apps.googleusercontent.com',
    iosBundleId: 'com.ray.match5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzxUD73yhL26QR7urT6KRftm9l5lgqQKQ',
    appId: '1:264376487042:ios:4800b1e94383dece50789b',
    messagingSenderId: '264376487042',
    projectId: 'match5-9f06d',
    storageBucket: 'match5-9f06d.firebasestorage.app',
    androidClientId: '264376487042-hbbqjqgmotf1d59ip7hc3vua00dht0h6.apps.googleusercontent.com',
    iosClientId: '264376487042-3obn9kb2lrh7i5sl4bnatq2723jjv3ik.apps.googleusercontent.com',
    iosBundleId: 'com.ray.match5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW2aMq1KvfnLYpaDMMdxb5KxkoDSCcYxo',
    appId: '1:264376487042:web:fa374c7713d68c9250789b',
    messagingSenderId: '264376487042',
    projectId: 'match5-9f06d',
    authDomain: 'match5-9f06d.firebaseapp.com',
    storageBucket: 'match5-9f06d.firebasestorage.app',
    measurementId: 'G-EMVLMZJRWF',
  );

}