import 'dart:math';

import 'package:flutter/material.dart';

List<String> softQuestions = [
  "🤫 What’s one secret you’ve never told anyone?",
  "😳💘 Have you ever had a crush on someone you shouldn’t have?",
  "🙈 What’s the most embarrassing thing you’ve ever done?",
  "🎭😅 What’s something you pretend to like but actually don’t?",
  "😏🤥 What’s the biggest lie you’ve ever told and got away with?",
  "🔥😉 What’s your biggest turn-on?",
  "😨🕳️ What’s a secret fear you’ve never told anyone?",
  "⏳🔁 If you could change one thing about your past, what would it be?",
  "❤️🚨 Who’s the one person you’d drop everything for?",
  "🧠💬 What’s something you wish people understood about you?",
  "💖🌹 What’s the most romantic thing you’ve ever done for someone?",
  "😍💬 What’s the sexiest thing someone could say to you?",
  "👀💋 What part of a person do you find most attractive?",
  "💄👄🪞 Have you ever practiced kissing in the mirror?",
  "🤗💋 Would you rather cuddle or make out?",
  "📸😈 Have you ever sent a naughty pic?",
  "🎁🔥 Do you like giving or receiving more?",
  "🛏️😉 Have you ever had a “friends with benefits” situation?",
  "😴🩳❌ What do you wear to bed — or do you sleep naked?",
  "🔥🕒💥 What’s the most number of times you’ve done it in one day?"
];

List<String> hardQuestions = [
  "Are you more dominant, submissive, or a switch?",
  "What’s your favorite safe word — or would you want one?",
  "Have you ever been tied up, or tied someone else up?",
  "What’s your opinion on spanking — giving or receiving?",
  "What’s a BDSM act you’ve always wanted to try but haven’t?",
  "Would you ever let someone completely take control of you in the bedroom?",
  "What are your hard limits — things you’d never do?",
  "Would you ever wear a collar — or put one on someone else?",
  "Have you ever done orgasm control or denial?",
  "What’s your opinion on public BDSM (discreet play in public settings)?",
  "What’s one dirty command you’d love to be given — or give?",
  "Do you enjoy being punished? If yes, what kind of punishment turns you on?",
  "What’s your ultimate BDSM scene or fantasy?",
  "Have you ever been pushed to the point of safe-wording? What was the reason?",
];

List<Color?> colors = [
  Colors.pink[100],
  Colors.blue[100],
  Colors.green[100],
  Colors.orange[100],
  Colors.purple[100],
  Colors.teal[100],
];

String generateRandomName() {
  List<String> adjectives = [
    "Brave",
    "Chill",
    "Clever",
    "Cool",
    "Curious",
    "Daring",
    "Dark",
    "Dizzy",
    "Dreamy",
    "Eager",
    "Epic",
    "Funky",
    "Gentle",
    "Glowing",
    "Happy",
    "Hungry",
    "Icy",
    "Jolly",
    "Kind",
    "Lively",
    "Lucky",
    "Magic",
    "Mellow",
    "Mighty",
    "Moody",
    "Mystic",
    "Nimble",
    "Peppy",
    "Quick",
    "Quiet",
    "Radiant",
    "Rare",
    "Rapid",
    "Rogue",
    "Rowdy",
    "Royal",
    "Rusty",
    "Salty",
    "Savvy",
    "Shiny",
    "Silent",
    "Silly",
    "Sleepy",
    "Slow",
    "Smart",
    "Sneaky",
    "Snappy",
    "Soft",
    "Spicy",
    "Steady",
    "Stormy",
    "Strange",
    "Strong",
    "Sunny",
    "Swift",
    "Tame",
    "Thirsty",
    "Tiny",
    "Trendy",
    "Tricky",
    "Tough",
    "Unique",
    "Vast",
    "Vivid",
    "Warm",
    "Wavy",
    "Weird",
    "Wicked",
    "Wild",
    "Witty",
    "Zany",
    "Blazing",
    "Bubbly",
    "Crimson",
    "Golden",
    "Neon",
    "Shadowy",
    "Vibrant",
    "Ironic",
    "Snug",
    "Feisty",
    "Bright",
    "Snazzy",
    "Nifty",
    "Spunky",
    "Bold",
    "Scarlet",
    "Blissful",
    "Dusty",
    "Groovy",
    "Minty",
    "Sassy",
    "Jazzy",
    "Radiant",
    "Charming",
    "Bossy",
    "Dazzling",
    "Frosty",
    "Cozy",
    "Rustic"
  ];
  List<String> nouns = [
    "Tiger",
    "Otter",
    "Bear",
    "Fox",
    "Wolf",
    "Panda",
    "Lynx",
    "Hawk",
    "Dove",
    "Falcon",
    "Vibe",
    "Pixel",
    "Flame",
    "Wizard",
    "Rocket",
    "Star",
    "Spark",
    "Blaze",
    "Drift",
    "Glow",
    "Ghost",
    "Shade",
    "Storm",
    "Bliss",
    "Moon",
    "Nova",
    "Aura",
    "Frost",
    "Dust",
    "Bolt",
    "Quest",
    "Dash",
    "Hero",
    "Echo",
    "Ninja",
    "Scout",
    "Rider",
    "Seeker",
    "Surge",
    "Soul",
    "Buddy",
    "Agent",
    "Knight",
    "Sage",
    "Hunter",
    "Wanderer",
    "Beast",
    "Champion",
    "Legend",
    "Shifter",
    "Goblin",
    "Witch",
    "Phoenix",
    "Griffin",
    "Unicorn",
    "Dragon",
    "Elf",
    "Bandit",
    "Shadow",
    "Champion",
    "Bot",
    "Guru",
    "Bard",
    "Nomad",
    "Player",
    "Stranger",
    "Rebel",
    "Rogue",
    "Wizard",
    "Pirate",
    "Scholar",
    "Dreamer",
    "Speaker",
    "Chatter",
    "Blink",
    "Byte",
    "Circuit",
    "Cloud",
    "Signal",
    "Sparkle",
    "Orbit",
    "Path",
    "Portal",
    "Shell",
    "Scope",
    "Swipe",
    "Tune",
    "Verse",
    "Loop",
    "Mode",
    "Core",
    "Crush",
    "Trend",
    "Match",
    "Jewel",
    "Aura",
    "Pulse",
    "Zone",
    "Link",
    "Drop"
  ];

  final random = Random();
  String adj = adjectives[random.nextInt(adjectives.length)];
  String noun = nouns[random.nextInt(nouns.length)];
  int num = 100 + random.nextInt(900);

  return '$adj$noun$num';
}
